scalar UIConfig
scalar SavedFilterAST
scalar SavedUIOptions

extend type ConfigResult {
  ui: UIConfig!
}

extend type SavedFilter {
  filter_ast: SavedFilterAST
  ui_options: SavedUIOptions
}

extend input SaveFilterInput {
  filter_ast: SavedFilterAST
  ui_options: SavedUIOptions
}

extend input DefaultFilterInput {
  filter_ast: SavedFilterAST
  ui_options: SavedUIOptions
}

extend type Mutation {
  configureUI(input: Map, partial: Map): UIConfig!
  configureDefaultFilter(input: ConfigureDefaultFilterInput!): UIConfig!
}
