query FindImages(
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $image_filter_ast: FilterASTInput
  $image_ids: [Int!]
) {
  findImages(
    filter: $filter
    image_filter: $image_filter
    image_filter_ast: $image_filter_ast
    image_ids: $image_ids
  ) {
    count
    images {
      ...SlimImageData
    }
  }
}

query FindImagesMetadata(
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $image_filter_ast: FilterASTInput
  $image_ids: [Int!]
) {
  findImages(
    filter: $filter
    image_filter: $image_filter
    image_filter_ast: $image_filter_ast
    image_ids: $image_ids
  ) {
    megapixels
    filesize
  }
}

query FindImage($id: ID!, $checksum: String) {
  findImage(id: $id, checksum: $checksum) {
    ...ImageData
  }
}

query FindDuplicateImages($distance: Int!, $filter: FindFilterType) {
  findDuplicateImageGroups(distance: $distance, filter: $filter) {
    count
    groups {
      ...SlimImageData
    }
  }
}

query FindDuplicateImagesFiltered(
  $distance: Int!
  $filter: FindFilterType
  $image_filter: ImageFilterType
  $image_filter_ast: FilterASTInput
  $filter_mode: DuplicateFilterMode!
) {
  findDuplicateImageGroups(
    distance: $distance
    filter: $filter
    image_filter: $image_filter
    image_filter_ast: $image_filter_ast
    filter_mode: $filter_mode
  ) {
    count
    groups {
      ...SlimImageData
    }
  }
}
