query PluginSettings($plugin_id: ID!) {
  pluginSettings: pluginSettingsV3(plugin_id: $plugin_id) {
    definitions {
      name
      display_name
      description
      type
      default_value
      editor
      preview {
        entity
        description
      }
      options {
        value
        label
      }
    }
    values
  }
}

query PluginEvaluateJQ($expression: String!, $input: Any) {
  pluginEvaluateJQ(expression: $expression, input: $input)
}

query PluginEvaluateMappings($mappings: Map!, $input: Any) {
  pluginEvaluateMappings(mappings: $mappings, input: $input)
}

query PluginSettingPreview(
  $plugin_id: ID!
  $setting: String!
  $entity_id: ID!
) {
  pluginSettingPreviewV3(
    plugin_id: $plugin_id
    setting: $setting
    entity_id: $entity_id
  )
}

query PluginPreviewScenes($query: String!) {
  findScenes(
    filter: { q: $query, per_page: 20, sort: "updated_at", direction: DESC }
  ) {
    scenes {
      id
      title
      files {
        path
      }
    }
  }
}

query PluginPreviewImages($query: String!) {
  findImages(
    filter: { q: $query, per_page: 20, sort: "updated_at", direction: DESC }
  ) {
    images {
      id
      title
      visual_files {
        ... on BaseFile {
          path
        }
      }
    }
  }
}
