query FindScenes(
  $filter: FindFilterType
  $scene_filter: SceneFilterType
  $scene_filter_ast: FilterASTInput
  $scene_ids: [Int!]
) {
  findScenes(
    filter: $filter
    scene_filter: $scene_filter
    scene_filter_ast: $scene_filter_ast
    scene_ids: $scene_ids
  ) {
    count
    filesize
    duration
    scenes {
      ...SlimSceneData
    }
  }
}

query FindScenesMobile(
  $filter: FindFilterType
  $scene_filter: SceneFilterType
  $scene_filter_ast: FilterASTInput
) {
  findScenes(
    filter: $filter
    scene_filter: $scene_filter
    scene_filter_ast: $scene_filter_ast
  ) {
    count
    filesize
    duration
    scenes {
      ...MobileSceneData
    }
  }
}

query FindScenesByPathRegex($filter: FindFilterType) {
  findScenesByPathRegex(filter: $filter) {
    count
    filesize
    duration
    scenes {
      ...SlimSceneData
    }
  }
}

query FindDuplicateScenes(
  $distance: Int
  $duration_diff: Float
  $filter: FindFilterType
) {
  findDuplicateSceneGroups(
    distance: $distance
    duration_diff: $duration_diff
    filter: $filter
  ) {
    count
    groups {
      ...SlimSceneData
    }
  }
}

query FindDuplicateScenesFiltered(
  $distance: Int
  $duration_diff: Float
  $filter: FindFilterType
  $scene_filter: SceneFilterType
  $scene_filter_ast: FilterASTInput
  $filter_mode: DuplicateFilterMode!
) {
  findDuplicateSceneGroups(
    distance: $distance
    duration_diff: $duration_diff
    filter: $filter
    scene_filter: $scene_filter
    scene_filter_ast: $scene_filter_ast
    filter_mode: $filter_mode
  ) {
    count
    groups {
      ...SlimSceneData
    }
  }
}

query FindScene($id: ID!, $checksum: String) {
  findScene(id: $id, checksum: $checksum) {
    ...SceneData
  }
}

query FindFullScenes($ids: [Int!]) {
  findScenes(scene_ids: $ids) {
    scenes {
      ...SceneData
    }
  }
}

query FindSceneMarkerTags($id: ID!) {
  sceneMarkerTags(scene_id: $id) {
    tag {
      id
      name
    }
    scene_markers {
      ...SceneMarkerData
    }
  }
}

query ParseSceneFilenames(
  $filter: FindFilterType!
  $config: SceneParserInput!
) {
  parseSceneFilenames(filter: $filter, config: $config) {
    count
    results {
      scene {
        ...SlimSceneData
      }
      title
      code
      details
      director
      url
      date
      rating
      studio_id
      gallery_ids
      movies {
        movie_id
      }
      performer_ids
      tag_ids
    }
  }
}

query SceneStreams($id: ID!) {
  findScene(id: $id) {
    sceneStreams: sceneStreamsV3 {
      url
      mime_type
      label
    }
  }
}

query FindScenesForSelect(
  $filter: FindFilterType
  $scene_filter: SceneFilterType
  $scene_filter_ast: FilterASTInput
  $ids: [ID!]
) {
  findScenes(
    filter: $filter
    scene_filter: $scene_filter
    scene_filter_ast: $scene_filter_ast
    ids: $ids
  ) {
    count
    scenes {
      ...SelectSceneData
    }
  }
}
