package api

import (
	"context"

	"github.com/stashapp/stash/internal/api/urlbuilders"
	"github.com/stashapp/stash/internal/manager"
	"github.com/stashapp/stash/internal/manager/config"
	"github.com/stashapp/stash/pkg/fsutil"
	"github.com/stashapp/stash/pkg/models"
)

func (r *sceneMarkerResolver) Scene(ctx context.Context, obj *models.SceneMarker) (ret *models.Scene, err error) {
	if err := r.withReadTxn(ctx, func(ctx context.Context) error {
		ret, err = r.repository.Scene.Find(ctx, obj.SceneID)
		return err
	}); err != nil {
		return nil, err
	}

	return ret, nil
}

func (r *sceneMarkerResolver) PrimaryTag(ctx context.Context, obj *models.SceneMarker) (ret *models.Tag, err error) {
	if err := r.withReadTxn(ctx, func(ctx context.Context) error {
		ret, err = r.repository.Tag.Find(ctx, obj.PrimaryTagID)
		return err
	}); err != nil {
		return nil, err
	}

	return ret, err
}

func (r *sceneMarkerResolver) Tags(ctx context.Context, obj *models.SceneMarker) (ret []*models.Tag, err error) {
	if err := r.withReadTxn(ctx, func(ctx context.Context) error {
		ret, err = r.repository.Tag.FindBySceneMarkerID(ctx, obj.ID)
		return err
	}); err != nil {
		return nil, err
	}

	return ret, err
}

func (r *sceneMarkerResolver) Stream(ctx context.Context, obj *models.SceneMarker) (string, error) {
	// `marker.stream` returns the URL of the marker's mp4 video preview —
	// the file optionally generated by the marker-preview task. Return
	// an empty string when the file doesn't exist so card hover previews
	// don't fire 404s for markers whose video preview was never
	// generated. (Mirror of `scene.paths.preview`'s file-existence check
	// in resolver_model_scene.go.)
	var scene *models.Scene
	if err := r.withReadTxn(ctx, func(ctx context.Context) error {
		var err error
		scene, err = r.repository.Scene.Find(ctx, obj.SceneID)
		return err
	}); err != nil {
		return "", err
	}
	if scene == nil {
		return "", nil
	}
	hash := scene.GetHash(config.GetInstance().GetVideoFileNamingAlgorithm())
	previewPath := manager.GetInstance().Paths.SceneMarkers.GetVideoPreviewPath(hash, int(obj.Seconds))
	if exists, _ := fsutil.FileExists(previewPath); !exists {
		return "", nil
	}
	baseURL, _ := ctx.Value(BaseURLCtxKey).(string)
	return urlbuilders.NewSceneMarkerURLBuilder(baseURL, obj).GetStreamURL(), nil
}

func (r *sceneMarkerResolver) Preview(ctx context.Context, obj *models.SceneMarker) (string, error) {
	// `marker.preview` is the URL of the animated WebP generated by the
	// marker-preview task. Return an empty string when the file doesn't
	// exist so card idle/hover previews skip requesting a missing asset
	// (mirrors `marker.stream` above and `scene.paths.webp`).
	var scene *models.Scene
	if err := r.withReadTxn(ctx, func(ctx context.Context) error {
		var err error
		scene, err = r.repository.Scene.Find(ctx, obj.SceneID)
		return err
	}); err != nil {
		return "", err
	}
	if scene == nil {
		return "", nil
	}
	hash := scene.GetHash(config.GetInstance().GetVideoFileNamingAlgorithm())
	previewPath := manager.GetInstance().Paths.SceneMarkers.GetWebpPreviewPath(hash, int(obj.Seconds))
	if exists, _ := fsutil.FileExists(previewPath); !exists {
		return "", nil
	}
	baseURL, _ := ctx.Value(BaseURLCtxKey).(string)
	return urlbuilders.NewSceneMarkerURLBuilder(baseURL, obj).GetPreviewURL(), nil
}

func (r *sceneMarkerResolver) Screenshot(ctx context.Context, obj *models.SceneMarker) (string, error) {
	baseURL, _ := ctx.Value(BaseURLCtxKey).(string)
	return urlbuilders.NewSceneMarkerURLBuilder(baseURL, obj).GetScreenshotURL(), nil
}
