import {
  Settings,
  Eye,
  Info,
  Star,
  Droplets,
  Check,
  Tags,
  Tag,
  BookmarkPlus,
  Bookmark,
  Trash2,
  RotateCw,
  Maximize,
  Volume2,
  Expand,
  Repeat,
  Gauge,
  Captions,
  SlidersHorizontal,
  CircleHelp,
  Heart,
  Flame,
  Sparkles,
  Plus,
  Folder,
  type LucideIcon,
} from "lucide-react";
import type { TvAction, TvActionKind } from "@/core/tv/action-config";

export const tvActionLabels: Record<TvActionKind, string> = {
  settings: "TV settings",
  visibility: "Show or hide controls",
  info: "Information",
  rating: "Rating",
  counter: "O-counter",
  organized: "Organized",
  tags: "Edit tags",
  "quick-tag": "Quick tag",
  marker: "Create marker",
  "quick-marker": "Quick marker",
  delete: "Delete current item",
  rotation: "Rotate presentation",
  fullscreen: "Immersive / fullscreen",
  volume: "Volume",
  fit: "Fit or fill",
  completion: "Playback mode",
  speed: "Playback speed",
  subtitles: "Subtitles",
  quality: "Quality",
  help: "TV guide",
};
const icons: Record<TvActionKind, LucideIcon> = {
  settings: Settings,
  visibility: Eye,
  info: Info,
  rating: Star,
  counter: Droplets,
  organized: Check,
  tags: Tags,
  "quick-tag": Tag,
  marker: BookmarkPlus,
  "quick-marker": Bookmark,
  delete: Trash2,
  rotation: RotateCw,
  fullscreen: Maximize,
  volume: Volume2,
  fit: Expand,
  completion: Repeat,
  speed: Gauge,
  subtitles: Captions,
  quality: SlidersHorizontal,
  help: CircleHelp,
};
export const tvCustomIcons = {
  default: Folder,
  heart: Heart,
  star: Star,
  tag: Tag,
  bookmark: Bookmark,
  flame: Flame,
  sparkles: Sparkles,
  check: Check,
  plus: Plus,
} satisfies Record<TvAction["icon"], LucideIcon>;
export function tvActionIcon(action: TvAction): LucideIcon {
  return action.icon === "default"
    ? icons[action.kind]
    : tvCustomIcons[action.icon];
}
