/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SceneDuplicateCheckerRouteImport } from './routes/scene-duplicate-checker'
import { Route as ImageDuplicateCheckerRouteImport } from './routes/image-duplicate-checker'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsIndexRouteImport } from './routes/tags/index'
import { Route as StudiosIndexRouteImport } from './routes/studios/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScenesIndexRouteImport } from './routes/scenes/index'
import { Route as PerformersIndexRouteImport } from './routes/performers/index'
import { Route as OfflineIndexRouteImport } from './routes/offline/index'
import { Route as ImagesIndexRouteImport } from './routes/images/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GalleriesIndexRouteImport } from './routes/galleries/index'
import { Route as TagsTagIdRouteImport } from './routes/tags/$tagId'
import { Route as StudiosStudioIdRouteImport } from './routes/studios/$studioId'
import { Route as SettingsToolsRouteImport } from './routes/settings/tools'
import { Route as SettingsTasksRouteImport } from './routes/settings/tasks'
import { Route as SettingsSystemRouteImport } from './routes/settings/system'
import { Route as SettingsServicesRouteImport } from './routes/settings/services'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsMetadataProvidersRouteImport } from './routes/settings/metadata-providers'
import { Route as SettingsLogsRouteImport } from './routes/settings/logs'
import { Route as SettingsLibraryRouteImport } from './routes/settings/library'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ScenesMarkersRouteImport } from './routes/scenes/markers'
import { Route as ScenesSceneIdRouteImport } from './routes/scenes/$sceneId'
import { Route as PerformersPerformerIdRouteImport } from './routes/performers/$performerId'
import { Route as OfflineSceneIdRouteImport } from './routes/offline/$sceneId'
import { Route as ImagesImageIdRouteImport } from './routes/images/$imageId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as GalleriesGalleryIdRouteImport } from './routes/galleries/$galleryId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SceneDuplicateCheckerRoute = SceneDuplicateCheckerRouteImport.update({
  id: '/scene-duplicate-checker',
  path: '/scene-duplicate-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageDuplicateCheckerRoute = ImageDuplicateCheckerRouteImport.update({
  id: '/image-duplicate-checker',
  path: '/image-duplicate-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosIndexRoute = StudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ScenesIndexRoute = ScenesIndexRouteImport.update({
  id: '/scenes/',
  path: '/scenes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformersIndexRoute = PerformersIndexRouteImport.update({
  id: '/performers/',
  path: '/performers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineIndexRoute = OfflineIndexRouteImport.update({
  id: '/offline/',
  path: '/offline/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesIndexRoute = ImagesIndexRouteImport.update({
  id: '/images/',
  path: '/images/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesIndexRoute = GalleriesIndexRouteImport.update({
  id: '/galleries/',
  path: '/galleries/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagIdRoute = TagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosStudioIdRoute = StudiosStudioIdRouteImport.update({
  id: '/studios/$studioId',
  path: '/studios/$studioId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTasksRoute = SettingsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSystemRoute = SettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsServicesRoute = SettingsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMetadataProvidersRoute =
  SettingsMetadataProvidersRouteImport.update({
    id: '/metadata-providers',
    path: '/metadata-providers',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsLogsRoute = SettingsLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLibraryRoute = SettingsLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ScenesMarkersRoute = ScenesMarkersRouteImport.update({
  id: '/scenes/markers',
  path: '/scenes/markers',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesSceneIdRoute = ScenesSceneIdRouteImport.update({
  id: '/scenes/$sceneId',
  path: '/scenes/$sceneId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformersPerformerIdRoute = PerformersPerformerIdRouteImport.update({
  id: '/performers/$performerId',
  path: '/performers/$performerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineSceneIdRoute = OfflineSceneIdRouteImport.update({
  id: '/offline/$sceneId',
  path: '/offline/$sceneId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesImageIdRoute = ImagesImageIdRouteImport.update({
  id: '/images/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriesGalleryIdRoute = GalleriesGalleryIdRouteImport.update({
  id: '/galleries/$galleryId',
  path: '/galleries/$galleryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-duplicate-checker': typeof ImageDuplicateCheckerRoute
  '/scene-duplicate-checker': typeof SceneDuplicateCheckerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/test': typeof TestRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/offline/$sceneId': typeof OfflineSceneIdRoute
  '/performers/$performerId': typeof PerformersPerformerIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
  '/scenes/markers': typeof ScenesMarkersRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-providers': typeof SettingsMetadataProvidersRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tasks': typeof SettingsTasksRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/offline/': typeof OfflineIndexRoute
  '/performers/': typeof PerformersIndexRoute
  '/scenes/': typeof ScenesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-duplicate-checker': typeof ImageDuplicateCheckerRoute
  '/scene-duplicate-checker': typeof SceneDuplicateCheckerRoute
  '/stats': typeof StatsRoute
  '/test': typeof TestRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/offline/$sceneId': typeof OfflineSceneIdRoute
  '/performers/$performerId': typeof PerformersPerformerIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
  '/scenes/markers': typeof ScenesMarkersRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-providers': typeof SettingsMetadataProvidersRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tasks': typeof SettingsTasksRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/galleries': typeof GalleriesIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/images': typeof ImagesIndexRoute
  '/offline': typeof OfflineIndexRoute
  '/performers': typeof PerformersIndexRoute
  '/scenes': typeof ScenesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/studios': typeof StudiosIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-duplicate-checker': typeof ImageDuplicateCheckerRoute
  '/scene-duplicate-checker': typeof SceneDuplicateCheckerRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/test': typeof TestRoute
  '/galleries/$galleryId': typeof GalleriesGalleryIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/images/$imageId': typeof ImagesImageIdRoute
  '/offline/$sceneId': typeof OfflineSceneIdRoute
  '/performers/$performerId': typeof PerformersPerformerIdRoute
  '/scenes/$sceneId': typeof ScenesSceneIdRoute
  '/scenes/markers': typeof ScenesMarkersRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/library': typeof SettingsLibraryRoute
  '/settings/logs': typeof SettingsLogsRoute
  '/settings/metadata-providers': typeof SettingsMetadataProvidersRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/services': typeof SettingsServicesRoute
  '/settings/system': typeof SettingsSystemRoute
  '/settings/tasks': typeof SettingsTasksRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/studios/$studioId': typeof StudiosStudioIdRoute
  '/tags/$tagId': typeof TagsTagIdRoute
  '/galleries/': typeof GalleriesIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/images/': typeof ImagesIndexRoute
  '/offline/': typeof OfflineIndexRoute
  '/performers/': typeof PerformersIndexRoute
  '/scenes/': typeof ScenesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image-duplicate-checker'
    | '/scene-duplicate-checker'
    | '/settings'
    | '/stats'
    | '/test'
    | '/galleries/$galleryId'
    | '/groups/$groupId'
    | '/images/$imageId'
    | '/offline/$sceneId'
    | '/performers/$performerId'
    | '/scenes/$sceneId'
    | '/scenes/markers'
    | '/settings/about'
    | '/settings/library'
    | '/settings/logs'
    | '/settings/metadata-providers'
    | '/settings/plugins'
    | '/settings/security'
    | '/settings/services'
    | '/settings/system'
    | '/settings/tasks'
    | '/settings/tools'
    | '/studios/$studioId'
    | '/tags/$tagId'
    | '/galleries/'
    | '/groups/'
    | '/images/'
    | '/offline/'
    | '/performers/'
    | '/scenes/'
    | '/settings/'
    | '/studios/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image-duplicate-checker'
    | '/scene-duplicate-checker'
    | '/stats'
    | '/test'
    | '/galleries/$galleryId'
    | '/groups/$groupId'
    | '/images/$imageId'
    | '/offline/$sceneId'
    | '/performers/$performerId'
    | '/scenes/$sceneId'
    | '/scenes/markers'
    | '/settings/about'
    | '/settings/library'
    | '/settings/logs'
    | '/settings/metadata-providers'
    | '/settings/plugins'
    | '/settings/security'
    | '/settings/services'
    | '/settings/system'
    | '/settings/tasks'
    | '/settings/tools'
    | '/studios/$studioId'
    | '/tags/$tagId'
    | '/galleries'
    | '/groups'
    | '/images'
    | '/offline'
    | '/performers'
    | '/scenes'
    | '/settings'
    | '/studios'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/image-duplicate-checker'
    | '/scene-duplicate-checker'
    | '/settings'
    | '/stats'
    | '/test'
    | '/galleries/$galleryId'
    | '/groups/$groupId'
    | '/images/$imageId'
    | '/offline/$sceneId'
    | '/performers/$performerId'
    | '/scenes/$sceneId'
    | '/scenes/markers'
    | '/settings/about'
    | '/settings/library'
    | '/settings/logs'
    | '/settings/metadata-providers'
    | '/settings/plugins'
    | '/settings/security'
    | '/settings/services'
    | '/settings/system'
    | '/settings/tasks'
    | '/settings/tools'
    | '/studios/$studioId'
    | '/tags/$tagId'
    | '/galleries/'
    | '/groups/'
    | '/images/'
    | '/offline/'
    | '/performers/'
    | '/scenes/'
    | '/settings/'
    | '/studios/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageDuplicateCheckerRoute: typeof ImageDuplicateCheckerRoute
  SceneDuplicateCheckerRoute: typeof SceneDuplicateCheckerRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  TestRoute: typeof TestRoute
  GalleriesGalleryIdRoute: typeof GalleriesGalleryIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  ImagesImageIdRoute: typeof ImagesImageIdRoute
  OfflineSceneIdRoute: typeof OfflineSceneIdRoute
  PerformersPerformerIdRoute: typeof PerformersPerformerIdRoute
  ScenesSceneIdRoute: typeof ScenesSceneIdRoute
  ScenesMarkersRoute: typeof ScenesMarkersRoute
  StudiosStudioIdRoute: typeof StudiosStudioIdRoute
  TagsTagIdRoute: typeof TagsTagIdRoute
  GalleriesIndexRoute: typeof GalleriesIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ImagesIndexRoute: typeof ImagesIndexRoute
  OfflineIndexRoute: typeof OfflineIndexRoute
  PerformersIndexRoute: typeof PerformersIndexRoute
  ScenesIndexRoute: typeof ScenesIndexRoute
  StudiosIndexRoute: typeof StudiosIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scene-duplicate-checker': {
      id: '/scene-duplicate-checker'
      path: '/scene-duplicate-checker'
      fullPath: '/scene-duplicate-checker'
      preLoaderRoute: typeof SceneDuplicateCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-duplicate-checker': {
      id: '/image-duplicate-checker'
      path: '/image-duplicate-checker'
      fullPath: '/image-duplicate-checker'
      preLoaderRoute: typeof ImageDuplicateCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/': {
      id: '/studios/'
      path: '/studios'
      fullPath: '/studios/'
      preLoaderRoute: typeof StudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/scenes/': {
      id: '/scenes/'
      path: '/scenes'
      fullPath: '/scenes/'
      preLoaderRoute: typeof ScenesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performers/': {
      id: '/performers/'
      path: '/performers'
      fullPath: '/performers/'
      preLoaderRoute: typeof PerformersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline/': {
      id: '/offline/'
      path: '/offline'
      fullPath: '/offline/'
      preLoaderRoute: typeof OfflineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/': {
      id: '/images/'
      path: '/images'
      fullPath: '/images/'
      preLoaderRoute: typeof ImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/': {
      id: '/galleries/'
      path: '/galleries'
      fullPath: '/galleries/'
      preLoaderRoute: typeof GalleriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagId': {
      id: '/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/tags/$tagId'
      preLoaderRoute: typeof TagsTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/$studioId': {
      id: '/studios/$studioId'
      path: '/studios/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof StudiosStudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tools': {
      id: '/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof SettingsToolsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/tasks': {
      id: '/settings/tasks'
      path: '/tasks'
      fullPath: '/settings/tasks'
      preLoaderRoute: typeof SettingsTasksRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/system': {
      id: '/settings/system'
      path: '/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof SettingsSystemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/services': {
      id: '/settings/services'
      path: '/services'
      fullPath: '/settings/services'
      preLoaderRoute: typeof SettingsServicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/metadata-providers': {
      id: '/settings/metadata-providers'
      path: '/metadata-providers'
      fullPath: '/settings/metadata-providers'
      preLoaderRoute: typeof SettingsMetadataProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/logs': {
      id: '/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof SettingsLogsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/library': {
      id: '/settings/library'
      path: '/library'
      fullPath: '/settings/library'
      preLoaderRoute: typeof SettingsLibraryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/scenes/markers': {
      id: '/scenes/markers'
      path: '/scenes/markers'
      fullPath: '/scenes/markers'
      preLoaderRoute: typeof ScenesMarkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes/$sceneId': {
      id: '/scenes/$sceneId'
      path: '/scenes/$sceneId'
      fullPath: '/scenes/$sceneId'
      preLoaderRoute: typeof ScenesSceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performers/$performerId': {
      id: '/performers/$performerId'
      path: '/performers/$performerId'
      fullPath: '/performers/$performerId'
      preLoaderRoute: typeof PerformersPerformerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline/$sceneId': {
      id: '/offline/$sceneId'
      path: '/offline/$sceneId'
      fullPath: '/offline/$sceneId'
      preLoaderRoute: typeof OfflineSceneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$imageId': {
      id: '/images/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleries/$galleryId': {
      id: '/galleries/$galleryId'
      path: '/galleries/$galleryId'
      fullPath: '/galleries/$galleryId'
      preLoaderRoute: typeof GalleriesGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsLibraryRoute: typeof SettingsLibraryRoute
  SettingsLogsRoute: typeof SettingsLogsRoute
  SettingsMetadataProvidersRoute: typeof SettingsMetadataProvidersRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsServicesRoute: typeof SettingsServicesRoute
  SettingsSystemRoute: typeof SettingsSystemRoute
  SettingsTasksRoute: typeof SettingsTasksRoute
  SettingsToolsRoute: typeof SettingsToolsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsLibraryRoute: SettingsLibraryRoute,
  SettingsLogsRoute: SettingsLogsRoute,
  SettingsMetadataProvidersRoute: SettingsMetadataProvidersRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsServicesRoute: SettingsServicesRoute,
  SettingsSystemRoute: SettingsSystemRoute,
  SettingsTasksRoute: SettingsTasksRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageDuplicateCheckerRoute: ImageDuplicateCheckerRoute,
  SceneDuplicateCheckerRoute: SceneDuplicateCheckerRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  TestRoute: TestRoute,
  GalleriesGalleryIdRoute: GalleriesGalleryIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  ImagesImageIdRoute: ImagesImageIdRoute,
  OfflineSceneIdRoute: OfflineSceneIdRoute,
  PerformersPerformerIdRoute: PerformersPerformerIdRoute,
  ScenesSceneIdRoute: ScenesSceneIdRoute,
  ScenesMarkersRoute: ScenesMarkersRoute,
  StudiosStudioIdRoute: StudiosStudioIdRoute,
  TagsTagIdRoute: TagsTagIdRoute,
  GalleriesIndexRoute: GalleriesIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ImagesIndexRoute: ImagesIndexRoute,
  OfflineIndexRoute: OfflineIndexRoute,
  PerformersIndexRoute: PerformersIndexRoute,
  ScenesIndexRoute: ScenesIndexRoute,
  StudiosIndexRoute: StudiosIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
