// Generated by scripts/generate-settings-search-index.mjs — do not edit.
// Regenerate with `pnpm run gen-settings-index` after changing settings rows.

export interface SettingsSearchMessage {
  id: string;
  defaultMessage: string;
}

export interface SettingsSearchEntry {
  /** Settings page route the row lives on. */
  to: string;
  /** Enclosing SettingsSection title, when there is one. */
  section: SettingsSearchMessage | null;
  label: SettingsSearchMessage;
  description?: SettingsSearchMessage;
}

export const SETTINGS_SEARCH_INDEX: SettingsSearchEntry[] = [
  {
    to: "/settings/about",
    section: {
      id: "config.about.version",
      defaultMessage: "Version",
    },
    label: {
      id: "config.about.build_time",
      defaultMessage: "Build time",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.basic_settings",
      defaultMessage: "Basic settings",
    },
    label: {
      id: "config.ui.language.heading",
      defaultMessage: "Language",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.basic_settings",
      defaultMessage: "Basic settings",
    },
    label: {
      id: "theme.label",
      defaultMessage: "Theme",
    },
    description: {
      id: "theme.description",
      defaultMessage: "Choose your preferred colour scheme.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.basic_settings",
      defaultMessage: "Basic settings",
    },
    label: {
      id: "config.ui.custom_title.heading",
      defaultMessage: "Custom title",
    },
    description: {
      id: "config.ui.custom_title.description",
      defaultMessage: "Custom title to show in the browser tab.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.basic_settings",
      defaultMessage: "Basic settings",
    },
    label: {
      id: "config.ui.abbreviate_counters.heading",
      defaultMessage: "Abbreviate counters",
    },
    description: {
      id: "config.ui.abbreviate_counters.description",
      defaultMessage:
        "Display counters such as 1.2K instead of the full number.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_player.heading",
      defaultMessage: "Scene player",
    },
    label: {
      id: "config.ui.scene_player.options.auto_start_video",
      defaultMessage: "Auto-start video",
    },
    description: {
      id: "auto_start_video.description",
      defaultMessage: "Start playback automatically when a scene opens.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_player.heading",
      defaultMessage: "Scene player",
    },
    label: {
      id: "config.ui.scene_player.options.always_start_from_beginning",
      defaultMessage: "Always start from the beginning",
    },
    description: {
      id: "config.ui.scene_player.options.always_start_from_beginning_description",
      defaultMessage:
        "Ignore the saved resume position when opening a scene and start from the beginning instead. Deep links and marker clicks still seek to their target.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_player.heading",
      defaultMessage: "Scene player",
    },
    label: {
      id: "config.ui.scene_player.options.show_range_markers",
      defaultMessage: "Show range markers",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_player.heading",
      defaultMessage: "Scene player",
    },
    label: {
      id: "config.ui.scene_player.options.track_activity",
      defaultMessage: "Track activity",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_player.heading",
      defaultMessage: "Scene player",
    },
    label: {
      id: "config.ui.minimum_play_percent.heading",
      defaultMessage: "Minimum play percent",
    },
    description: {
      id: "config.ui.minimum_play_percent.description",
      defaultMessage:
        "The minimum percentage a scene must be played before the play count is incremented.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_list.heading",
      defaultMessage: "Scene list",
    },
    label: {
      id: "config.ui.preview_default.heading",
      defaultMessage: "Card preview default",
    },
    description: {
      id: "config.ui.preview_default.description",
      defaultMessage: "What list cards (grid and wall) show when not hovered.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.scene_list.heading",
      defaultMessage: "Scene list",
    },
    label: {
      id: "config.ui.play_video_on_hover.heading",
      defaultMessage: "Play video on hover",
    },
    description: {
      id: "config.ui.play_video_on_hover.description",
      defaultMessage:
        "Swap card previews to the video when you hover them. No effect when the default is already Video.",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.editing.heading",
      defaultMessage: "Editing",
    },
    label: {
      id: "config.ui.editing.rating_system.type.label",
      defaultMessage: "Rating system",
    },
  },
  {
    to: "/settings/interface",
    section: {
      id: "config.ui.editing.heading",
      defaultMessage: "Editing",
    },
    label: {
      id: "config.ui.editing.rating_system.star_precision.label",
      defaultMessage: "Star precision",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.media_content_extensions",
      defaultMessage: "Media content extensions",
    },
    label: {
      id: "config.general.video_ext_head",
      defaultMessage: "Video extensions",
    },
    description: {
      id: "config.general.video_ext_desc",
      defaultMessage:
        "Comma-delimited list of file extensions that will be identified as videos.",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.media_content_extensions",
      defaultMessage: "Media content extensions",
    },
    label: {
      id: "config.general.image_ext_head",
      defaultMessage: "Image extensions",
    },
    description: {
      id: "config.general.image_ext_desc",
      defaultMessage:
        "Comma-delimited list of file extensions that will be identified as images.",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.media_content_extensions",
      defaultMessage: "Media content extensions",
    },
    label: {
      id: "config.general.gallery_ext_head",
      defaultMessage: "Gallery extensions",
    },
    description: {
      id: "config.general.gallery_ext_desc",
      defaultMessage:
        "Comma-delimited list of file extensions that will be identified as gallery zip files.",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.exclusions",
      defaultMessage: "Exclusions",
    },
    label: {
      id: "config.general.excluded_video_patterns_head",
      defaultMessage: "Excluded video patterns",
    },
    description: {
      id: "config.general.excluded_video_patterns_desc",
      defaultMessage:
        "Regexps of video files/paths to exclude from scan and add to clean",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.exclusions",
      defaultMessage: "Exclusions",
    },
    label: {
      id: "config.general.excluded_image_gallery_patterns_head",
      defaultMessage: "Excluded image/gallery patterns",
    },
    description: {
      id: "config.general.excluded_image_gallery_patterns_desc",
      defaultMessage:
        "Regexps of image and gallery files/paths to exclude from scan and add to clean",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.gallery_and_image_options",
      defaultMessage: "Gallery and image options",
    },
    label: {
      id: "config.general.create_galleries_from_folders_label",
      defaultMessage: "Create galleries from folders containing images",
    },
    description: {
      id: "config.general.create_galleries_from_folders_desc",
      defaultMessage:
        "If true, creates galleries from folders containing images.",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.gallery_and_image_options",
      defaultMessage: "Gallery and image options",
    },
    label: {
      id: "config.ui.images.options.write_image_thumbnails.heading",
      defaultMessage: "Write image thumbnails",
    },
    description: {
      id: "config.ui.images.options.write_image_thumbnails.description",
      defaultMessage:
        "Write image thumbnails to disk when generated on the fly",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.gallery_and_image_options",
      defaultMessage: "Gallery and image options",
    },
    label: {
      id: "config.ui.images.options.create_image_clips_from_videos.heading",
      defaultMessage: "Create image clips from videos",
    },
    description: {
      id: "config.ui.images.options.create_image_clips_from_videos.description",
      defaultMessage:
        "If true, creates image clips from video files in zip galleries and image-only paths.",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.library.gallery_and_image_options",
      defaultMessage: "Gallery and image options",
    },
    label: {
      id: "config.general.gallery_cover_regex_label",
      defaultMessage: "Gallery cover pattern",
    },
    description: {
      id: "config.general.gallery_cover_regex_desc",
      defaultMessage: "Regexp of image filenames to use as gallery cover",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.ui.delete_options.heading",
      defaultMessage: "Delete options",
    },
    label: {
      id: "config.ui.delete_options.options.delete_file",
      defaultMessage: "Delete file by default",
    },
  },
  {
    to: "/settings/library",
    section: {
      id: "config.ui.delete_options.heading",
      defaultMessage: "Delete options",
    },
    label: {
      id: "config.ui.delete_options.options.delete_generated_supporting_files",
      defaultMessage: "Delete generated supporting files by default",
    },
    description: {
      id: "config.ui.delete_options.description",
      defaultMessage: "Default delete-dialog options when deleting items.",
    },
  },
  {
    to: "/settings/metadata-providers",
    section: {
      id: "config.general.scraping",
      defaultMessage: "Scraping",
    },
    label: {
      id: "config.general.scraper_user_agent",
      defaultMessage: "Scraper user agent",
    },
    description: {
      id: "config.general.scraper_user_agent_desc",
      defaultMessage: "User-Agent string used during scrape HTTP requests",
    },
  },
  {
    to: "/settings/metadata-providers",
    section: {
      id: "config.general.scraping",
      defaultMessage: "Scraping",
    },
    label: {
      id: "config.general.chrome_cdp_path",
      defaultMessage: "Chrome CDP path",
    },
    description: {
      id: "config.general.chrome_cdp_path_desc",
      defaultMessage:
        "File path to the Chrome executable, or a remote address (starting with http:// or https://, for example http://localhost:9222/json/version) of a Chrome instance.",
    },
  },
  {
    to: "/settings/metadata-providers",
    section: {
      id: "config.general.scraping",
      defaultMessage: "Scraping",
    },
    label: {
      id: "config.general.check_for_insecure_certificates",
      defaultMessage: "Check for insecure certificates",
    },
    description: {
      id: "config.general.check_for_insecure_certificates_desc",
      defaultMessage:
        "Some sites use insecure SSL certificates. When unchecked the scraper skips the insecure certificates check.",
    },
  },
  {
    to: "/settings/metadata-providers",
    section: {
      id: "config.general.scraping",
      defaultMessage: "Scraping",
    },
    label: {
      id: "config.scraping.excluded_tag_patterns_head",
      defaultMessage: "Excluded tag patterns",
    },
    description: {
      id: "config.scraping.excluded_tag_patterns_desc",
      defaultMessage: "Regexps of tag names to exclude from scrape results",
    },
  },
  {
    to: "/settings/security",
    section: {
      id: "config.general.auth.authentication",
      defaultMessage: "Authentication",
    },
    label: {
      id: "config.general.auth.credentials.heading",
      defaultMessage: "Credentials",
    },
    description: {
      id: "config.general.auth.credentials.description",
      defaultMessage: "Username and password to access stash.",
    },
  },
  {
    to: "/settings/security",
    section: {
      id: "config.general.auth.authentication",
      defaultMessage: "Authentication",
    },
    label: {
      id: "config.general.auth.api_key",
      defaultMessage: "API key",
    },
    description: {
      id: "config.general.auth.api_key_desc",
      defaultMessage:
        "API key for authenticating external clients. Requires username and password to be set.",
    },
  },
  {
    to: "/settings/security",
    section: {
      id: "config.general.auth.authentication",
      defaultMessage: "Authentication",
    },
    label: {
      id: "config.general.auth.maximum_session_age",
      defaultMessage: "Maximum session age",
    },
    description: {
      id: "config.general.auth.maximum_session_age_desc",
      defaultMessage:
        "Maximum idle time before a login session is expired, in seconds.",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.server_display_name",
      defaultMessage: "Server display name",
    },
    description: {
      id: "config.dlna.server_display_name_desc",
      defaultMessage:
        "Display name for the DLNA server. Defaults to stash when empty.",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.server_port",
      defaultMessage: "Server port",
    },
    description: {
      id: "config.dlna.server_port_desc",
      defaultMessage: "Port to run the DLNA server on. Requires restart.",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.enabled_by_default",
      defaultMessage: "Enabled by default",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.network_interfaces",
      defaultMessage: "Network interfaces",
    },
    description: {
      id: "config.dlna.network_interfaces_desc",
      defaultMessage:
        "Network interfaces to run the DLNA server on. Empty for all interfaces.",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.default_ip_whitelist",
      defaultMessage: "Default IP whitelist",
    },
    description: {
      id: "config.dlna.default_ip_whitelist_desc",
      defaultMessage:
        "IP addresses allowed to use the DLNA service by default. Use * as a wildcard.",
    },
  },
  {
    to: "/settings/services",
    section: {
      id: "settings",
      defaultMessage: "Settings",
    },
    label: {
      id: "config.dlna.video_sort_order",
      defaultMessage: "Default video sort order",
    },
    description: {
      id: "config.dlna.video_sort_order_desc",
      defaultMessage: "Order to sort videos by default.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.generated_path_head",
      defaultMessage: "Generated path",
    },
    description: {
      id: "config.general.generated_files_location",
      defaultMessage:
        "Directory location for the generated files (previews, screenshots, sprites, etc.)",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.cache_path_head",
      defaultMessage: "Cache path",
    },
    description: {
      id: "config.general.cache_location",
      defaultMessage: "Directory location of the cache",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.scrapers_path.heading",
      defaultMessage: "Scrapers path",
    },
    description: {
      id: "config.general.scrapers_path.description",
      defaultMessage: "Directory location for scraper configuration files",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.plugins_path.heading",
      defaultMessage: "Plugins path",
    },
    description: {
      id: "config.general.plugins_path.description",
      defaultMessage: "Directory location for plugin configuration files",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.metadata_path.heading",
      defaultMessage: "Metadata path",
    },
    description: {
      id: "config.general.metadata_path.description",
      defaultMessage: "Directory location for metadata export",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.ui.performers.options.image_location.heading",
      defaultMessage: "Custom performer image location",
    },
    description: {
      id: "config.ui.performers.options.image_location.description",
      defaultMessage:
        "Directory location of images for performers (with filenames matching performer names)",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.ffmpeg.ffmpeg_path.heading",
      defaultMessage: "FFmpeg path",
    },
    description: {
      id: "config.general.ffmpeg.ffmpeg_path.description",
      defaultMessage: "Path to the ffmpeg executable",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.ffmpeg.ffprobe_path.heading",
      defaultMessage: "FFprobe path",
    },
    description: {
      id: "config.general.ffmpeg.ffprobe_path.description",
      defaultMessage: "Path to the ffprobe executable",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.ffmpeg.download_ffmpeg.heading",
      defaultMessage: "Download FFmpeg",
    },
    description: {
      id: "config.general.ffmpeg.download_ffmpeg.description",
      defaultMessage: "Downloads FFmpeg and FFprobe into the config directory",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.python_path.heading",
      defaultMessage: "Python path",
    },
    description: {
      id: "config.general.python_path.description",
      defaultMessage:
        "Path to the python executable, used by plugins and scrapers",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.backup_directory_path.heading",
      defaultMessage: "Backup directory path",
    },
    description: {
      id: "config.general.backup_directory_path.description",
      defaultMessage: "Directory location for database backups",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.application_paths.heading",
      defaultMessage: "Application paths",
    },
    label: {
      id: "config.general.delete_trash_path.heading",
      defaultMessage: "Delete trash path",
    },
    description: {
      id: "config.general.delete_trash_path.description",
      defaultMessage:
        "Directory files are moved to when deleted, rather than being permanently deleted",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.database",
      defaultMessage: "Database",
    },
    label: {
      id: "config.general.db_path_head",
      defaultMessage: "Database path",
    },
    description: {
      id: "config.general.sqlite_location",
      defaultMessage:
        "File location for the SQLite database (requires restart)",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.database",
      defaultMessage: "Database",
    },
    label: {
      id: "config.general.blobs_storage.heading",
      defaultMessage: "Blobs storage",
    },
    description: {
      id: "config.general.blobs_storage.description",
      defaultMessage: "Where binary data (images) is stored.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.database",
      defaultMessage: "Database",
    },
    label: {
      id: "config.general.blobs_path.heading",
      defaultMessage: "Blobs path",
    },
    description: {
      id: "config.general.blobs_path.description",
      defaultMessage:
        "Directory location to store binary data (when using filesystem storage)",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.hashing",
      defaultMessage: "Hashing",
    },
    label: {
      id: "config.general.calculate_md5_and_ohash_label",
      defaultMessage: "Calculate MD5 for videos",
    },
    description: {
      id: "config.general.calculate_md5_and_ohash_desc",
      defaultMessage:
        "Calculate MD5 checksum in addition to oshash. Enabling will cause initial scans to be slower.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.hashing",
      defaultMessage: "Hashing",
    },
    label: {
      id: "config.general.generated_file_naming_hash_head",
      defaultMessage: "Generated file naming hash",
    },
    description: {
      id: "config.general.generated_file_naming_hash_desc",
      defaultMessage: "Hash algorithm used for generated file names.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.maximum_transcode_size_head",
      defaultMessage: "Maximum transcode size",
    },
    description: {
      id: "config.general.maximum_transcode_size_desc",
      defaultMessage: "Maximum size for generated transcodes",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.maximum_streaming_transcode_size_head",
      defaultMessage: "Maximum streaming transcode size",
    },
    description: {
      id: "config.general.maximum_streaming_transcode_size_desc",
      defaultMessage: "Maximum size for transcoded streams",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.ffmpeg.hardware_acceleration.heading",
      defaultMessage: "FFmpeg hardware encoding",
    },
    description: {
      id: "config.general.ffmpeg.hardware_acceleration.desc",
      defaultMessage:
        "Use hardware acceleration when transcoding, if supported",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.ffmpeg.transcode.input_args.heading",
      defaultMessage: "FFmpeg transcode input args",
    },
    description: {
      id: "config.general.ffmpeg.transcode.input_args.desc",
      defaultMessage:
        "Advanced: additional ffmpeg input arguments for transcode generation",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.ffmpeg.transcode.output_args.heading",
      defaultMessage: "FFmpeg transcode output args",
    },
    description: {
      id: "config.general.ffmpeg.transcode.output_args.desc",
      defaultMessage:
        "Advanced: additional ffmpeg output arguments for transcode generation",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.ffmpeg.live_transcode.input_args.heading",
      defaultMessage: "FFmpeg live transcode input args",
    },
    description: {
      id: "config.general.ffmpeg.live_transcode.input_args.desc",
      defaultMessage:
        "Advanced: additional ffmpeg input arguments for live transcoding",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.system.transcoding",
      defaultMessage: "Transcoding",
    },
    label: {
      id: "config.general.ffmpeg.live_transcode.output_args.heading",
      defaultMessage: "FFmpeg live transcode output args",
    },
    description: {
      id: "config.general.ffmpeg.live_transcode.output_args.desc",
      defaultMessage:
        "Advanced: additional ffmpeg output arguments for live transcoding",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.parallel_scan_head",
      defaultMessage: "Parallel scan/generation",
    },
    label: {
      id: "config.general.number_of_parallel_task_for_scan_generation_head",
      defaultMessage: "Number of parallel tasks",
    },
    description: {
      id: "config.general.number_of_parallel_task_for_scan_generation_desc",
      defaultMessage:
        "Set to 0 for auto-detection. Warning: setting above the auto-detected value can decrease performance and cause issues.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "dialogs.scene_gen.preview_preset_head",
      defaultMessage: "Preview encoding preset",
    },
    description: {
      id: "dialogs.scene_gen.preview_preset_desc",
      defaultMessage:
        "The preset regulates size, quality and encoding time of preview generation.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "config.general.include_audio_head",
      defaultMessage: "Include audio",
    },
    description: {
      id: "config.general.include_audio_desc",
      defaultMessage: "Includes audio stream when generating previews.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "dialogs.scene_gen.preview_seg_count_head",
      defaultMessage: "Number of segments in preview",
    },
    description: {
      id: "dialogs.scene_gen.preview_seg_count_desc",
      defaultMessage: "Number of segments in preview files.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "dialogs.scene_gen.preview_seg_duration_head",
      defaultMessage: "Preview segment duration",
    },
    description: {
      id: "dialogs.scene_gen.preview_seg_duration_desc",
      defaultMessage: "Duration of each preview segment, in seconds.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "dialogs.scene_gen.preview_exclude_start_time_head",
      defaultMessage: "Exclude start time",
    },
    description: {
      id: "dialogs.scene_gen.preview_exclude_start_time_desc",
      defaultMessage:
        "Exclude the first x seconds from scene previews. This can be a value in seconds, or a percentage (eg 2%) of the total scene duration.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.preview_generation",
      defaultMessage: "Preview generation",
    },
    label: {
      id: "dialogs.scene_gen.preview_exclude_end_time_head",
      defaultMessage: "Exclude end time",
    },
    description: {
      id: "dialogs.scene_gen.preview_exclude_end_time_desc",
      defaultMessage:
        "Exclude the last x seconds from scene previews. This can be a value in seconds, or a percentage (eg 2%) of the total scene duration.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.sprite_generation_head",
      defaultMessage: "Sprite generation",
    },
    label: {
      id: "config.general.sprite_screenshot_size_head",
      defaultMessage: "Sprite screenshot size",
    },
    description: {
      id: "config.general.sprite_screenshot_size_desc",
      defaultMessage: "Width of the generated sprite screenshots, in pixels.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.sprite_generation_head",
      defaultMessage: "Sprite generation",
    },
    label: {
      id: "config.general.use_custom_sprite_interval_head",
      defaultMessage: "Use custom sprite interval",
    },
    description: {
      id: "config.general.use_custom_sprite_interval_desc",
      defaultMessage:
        "Use a fixed interval between sprite screenshots instead of a fixed count.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.sprite_generation_head",
      defaultMessage: "Sprite generation",
    },
    label: {
      id: "config.general.sprite_interval_head",
      defaultMessage: "Sprite interval",
    },
    description: {
      id: "config.general.sprite_interval_desc",
      defaultMessage:
        "Seconds between sprite screenshots when using a custom interval.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.sprite_generation_head",
      defaultMessage: "Sprite generation",
    },
    label: {
      id: "config.general.sprite_minimum_head",
      defaultMessage: "Minimum sprites",
    },
    description: {
      id: "config.general.sprite_minimum_desc",
      defaultMessage: "Minimum number of sprite screenshots per video.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.sprite_generation_head",
      defaultMessage: "Sprite generation",
    },
    label: {
      id: "config.general.sprite_maximum_head",
      defaultMessage: "Maximum sprites",
    },
    description: {
      id: "config.general.sprite_maximum_desc",
      defaultMessage: "Maximum number of sprite screenshots per video.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.heatmap_generation",
      defaultMessage: "Heatmap generation",
    },
    label: {
      id: "config.general.funscript_heatmap_draw_range",
      defaultMessage: "Draw funscript heatmap range",
    },
    description: {
      id: "config.general.funscript_heatmap_draw_range_desc",
      defaultMessage:
        "Draws the motion range into generated funscript heatmaps.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.logging",
      defaultMessage: "Logging",
    },
    label: {
      id: "config.general.auth.log_file",
      defaultMessage: "Log file",
    },
    description: {
      id: "config.general.auth.log_file_desc",
      defaultMessage:
        "Path to the file to output logging to. Blank to disable file logging. Requires restart.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.logging",
      defaultMessage: "Logging",
    },
    label: {
      id: "config.general.auth.log_to_terminal",
      defaultMessage: "Log to terminal",
    },
    description: {
      id: "config.general.auth.log_to_terminal_desc",
      defaultMessage:
        "Logs to the terminal in addition to a file. Always true if file logging is disabled. Requires restart.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.logging",
      defaultMessage: "Logging",
    },
    label: {
      id: "config.logs.log_level",
      defaultMessage: "Log level",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.logging",
      defaultMessage: "Logging",
    },
    label: {
      id: "config.general.auth.log_http",
      defaultMessage: "Log HTTP access",
    },
    description: {
      id: "config.general.auth.log_http_desc",
      defaultMessage: "Logs HTTP access to the terminal. Requires restart.",
    },
  },
  {
    to: "/settings/system",
    section: {
      id: "config.general.logging",
      defaultMessage: "Logging",
    },
    label: {
      id: "config.general.auth.log_file_max_size",
      defaultMessage: "Log file max size (MB)",
    },
    description: {
      id: "config.general.auth.log_file_max_size_desc",
      defaultMessage:
        "Maximum size of the log file in megabytes before it is rotated.",
    },
  },
  {
    to: "/settings/tools",
    section: {
      id: "config.tools.heading",
      defaultMessage: "Tools",
    },
    label: {
      id: "config.tools.graphql_playground",
      defaultMessage: "GraphQL playground",
    },
  },
  {
    to: "/settings/tools",
    section: {
      id: "config.tools.scene_tools",
      defaultMessage: "Scene tools",
    },
    label: {
      id: "config.tools.scene_duplicate_checker",
      defaultMessage: "Scene duplicate checker",
    },
  },
  {
    to: "/settings/tools",
    section: {
      id: "config.tools.image_tools",
      defaultMessage: "Image tools",
    },
    label: {
      id: "config.tools.image_duplicate_checker",
      defaultMessage: "Image duplicate checker",
    },
  },
];
