import { expect, it, vi } from "vitest";
import { account, ids } from "../../../tests/fixtures/account-review";
import { postMedia, postSummary } from "../../../tests/fixtures/source-posts";
import httpFixtures from "../../../tests/fixtures/review-queue-http.json";
import {
  createReviewQueueAPI,
  reviewQueueSearchSchema,
  type ReviewQueueItem,
  type ReviewQueueKind,
} from "./review-queue-api";

function client(body: unknown) {
  const transport = vi.fn<typeof fetch>(async () => Response.json(body));
  return {
    api: createReviewQueueAPI(
      "https://example.test/stash/api/v3/archive/",
      transport,
    ),
    transport,
  };
}
function item(kind: ReviewQueueKind): ReviewQueueItem {
  if (kind === "accounts")
    return {
      uuid: ids.account,
      reasons: ["account_owner_undecided"],
      account: account(),
    };
  if (kind === "media") {
    const post = postSummary();
    return { uuid: post.uuid, reasons: ["media_unselected"], post };
  }
  const media = postMedia().media;
  return { uuid: media.uuid, reasons: ["retained_metadata"], media };
}

it("accepts populated responses generated by the native HTTP handler", async () => {
  for (const kind of ["accounts", "media", "metadata"] as const) {
    const body = httpFixtures[kind];
    expect(await client(body).api.page(kind)).toEqual(body);
    expect(body.items).toHaveLength(1);
  }
});

it("uses the application session for read-only current review discovery", async () => {
  for (const kind of ["accounts", "media", "metadata"] as const) {
    const body = { kind, items: [item(kind)], checked: 1 };
    const { api, transport } = client(body);
    expect(await api.page(kind)).toEqual(body);
    const [address, options] = transport.mock.calls[0] ?? [];
    const url = new URL(String(address));
    expect(url.pathname).toBe(`/stash/api/v3/archive/review-queue/${kind}`);
    expect(Object.fromEntries(url.searchParams)).toEqual({ limit: "25" });
    expect(options).toMatchObject({
      method: "GET",
      credentials: "same-origin",
      cache: "no-store",
    });
    expect(options?.body).toBeUndefined();
  }
  expect(reviewQueueSearchSchema.parse({})).toEqual({ kind: "accounts" });
});

it("preserves an empty media page's continuation rather than claiming the queue is empty", async () => {
  const body = { kind: "media", items: [], checked: 100, next: ids.account };
  const { api } = client(body);
  expect(await api.page("media")).toEqual(body);
  await expect(api.page("media", ids.account)).rejects.toThrow();
  await expect(
    client({ ...body, checked: 0 }).api.page("media"),
  ).rejects.toThrow();
});

it("rejects mismatched subjects, settled accounts and unexpected review reasons", async () => {
  const current = item("accounts");
  for (const changed of [
    { ...current, uuid: ids.otherAccount },
    { ...current, account: { ...account(), canonical_uuid: ids.otherAccount } },
    { ...current, post: postSummary() },
    { ...current, reasons: ["retained_metadata"] },
    {
      ...current,
      reasons: ["account_owner_undecided", "account_owner_undecided"],
    },
    { ...current, settings: { secret: "must-not-be-here" } },
  ])
    await expect(
      client({ kind: "accounts", items: [changed], checked: 1 }).api.page(
        "accounts",
      ),
    ).rejects.toThrow();
  for (const state of ["linked", "unlinked"] as const) {
    const changed = {
      ...current,
      account: {
        ...account(),
        ownership: {
          decision_uuid: ids.decision,
          revision: 3,
          state,
          origin: "review",
          reason: "Already reviewed",
          created_at: "2026-10-07T00:00:00Z",
        },
      },
    };
    await expect(
      client({ kind: "accounts", items: [changed], checked: 1 }).api.page(
        "accounts",
      ),
    ).rejects.toThrow();
  }
  const media = item("media");
  await expect(
    client({
      kind: "media",
      items: [{ ...media, post: { ...postSummary(), state: "forgotten" } }],
      checked: 1,
    }).api.page("media"),
  ).rejects.toThrow();
  const metadata = item("metadata");
  await expect(
    client({
      kind: "metadata",
      items: [
        { ...metadata, media: { ...postMedia().media, kind: "gallery" } },
      ],
      checked: 1,
    }).api.page("metadata"),
  ).rejects.toThrow();
});

it("rejects invalid counters and non-advancing or duplicated entries", async () => {
  const current = item("accounts");
  for (const body of [
    { kind: "accounts", items: [current], checked: 0 },
    { kind: "accounts", items: [current], checked: 2 },
    { kind: "accounts", items: [current], checked: 1, next: ids.otherAccount },
    { kind: "accounts", items: [current, current], checked: 2 },
    { kind: "accounts", items: [], checked: 101 },
    { kind: "metadata", items: [current], checked: 1 },
  ])
    await expect(client(body).api.page("accounts")).rejects.toThrow();
  await expect(
    client({ kind: "accounts", items: [current], checked: 1 }).api.page(
      "accounts",
      current.uuid,
    ),
  ).rejects.toThrow();
});

it("validates cursors before transport and forwards cancellation", async () => {
  const { api, transport } = client({ kind: "media", items: [], checked: 0 });
  await expect(api.page("media", "bad")).rejects.toThrow();
  expect(transport).not.toHaveBeenCalled();
  const controller = new AbortController();
  await api.page("media", ids.account, controller.signal);
  expect(transport.mock.calls[0]?.[1]?.signal).toBe(controller.signal);
  expect(
    new URL(String(transport.mock.calls[0]?.[0])).searchParams.get("after"),
  ).toBe(ids.account);
});
